# Токен доступа VK
access_token = ""

# Пользователи, лайки и комментарии которых нужно искать в \\ group_ids \\
user_ids = [

]

# Группы, в которых искать лайки и комментарии пользователей \\ user_ids \\
group_ids = [

]

# Использовать группы пользователя, вместо \\ group_ids \\
is_groups_from_user = false
