# Токен доступа VK
access_token = ""

#------------------------------------

# Команда Friends
[friends]
# ID Пользователя
user_id = -1

#------------------------------------

# Команда Groups
[groups]
# Использовать группы пользователя, вместо \\ group_ids \\ (True or False)
is_groups_from_user = false

# Пользователи, лайки и комментарии которых нужно искать в \\ group_ids \\
user_ids = [
    
]

# Группы, в которых искать лайки и комментарии пользователей \\ user_ids \\
group_ids = [
    
]